### ISSUE TITLE
Shape Complementarity

### ISSUE THREAD

**Issue by jnarvaezp** [maxibor/meetdock#2]
Hi, 

I'm evaluating the shape complementarity of a set of proteins, but to evaluate the protein 5LQB the result I get score is zero, in the paper says it is zero when there is no contact, but if you look at the protein in Pymol this if you see the chains H and A, I was looking at FTT but I see that the calculations are good, can have some suggestion of what is happening? or can be a programming error?

Thanks for your help.  

JN

**Comment by maxibor** [comment]
Can you post the command used, and the meetdock log and output ?

**Comment by jnarvaezp** [comment]
Hi, 

I have currently created a program that implements the methods you designed, but the program only calculates the shape complmentarity, the program is based on shape_complement.py, but I haven't made any changes to the code.

This is the code: https://gist.github.com/jnarvaezp/766ea6a9f5b703b1b2901ce4a243d576

But when I use the full program I run the following command:
`meetdock /home/jonathan/Documents/Proteins/5/ -recChain L -ligChain H  -shape -depth naccess
`
Output
```
MultiProcessing available
Running on 12 threads
Computing scores for  5LQB.pdb
...
Traceback (most recent call last):
  File "meetdock", line 136, in <module>
    run_meetdock(mypath=mypath, myoutdir=myoutdir, ligChain="A", recChain="B", shape = shape, electro = electro, jones =jones, proba =proba, pH =pH, dist =dist, depth =depth, thread=thread)
  File "meetdock", line 129, in run_meetdock
    mydf = mydf.set_index('pdb')
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 4396, in set_index
    raise KeyError("None of {} are in the columns".format(missing))
KeyError: "None of ['pdb'] are in the columns"

```

meetdock /home/jonathan/Documents/Proteins/ -recChain L -ligChain H  -shape -depth naccess

Thanks for your help

**Comment by maxibor** [comment]
Hi @jnarvaezp,
The chain names were hardcoded somewhere, it's now fixed.

For the score of zero with shape complementarity, this might be explained because it is only computed for surface residues (as determined by msms or naccess) with a threshold that defines what is the surface.
Lowering this threshold might fix this issue.

https://github.com/maxibor/meetdock/blob/master/lib/pdb_resdepth.py
